version: "3.8"

services:
  mysql:
    container_name: mimi-mysql8
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: mimi
      # 0374 비밀번호는 왜 안먹히지????
      MYSQL_ROOT_PASSWORD: 1123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3374:3306"
  mysql-test:
    container_name: mimi-mysql8-test
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: mimi
      MYSQL_ROOT_PASSWORD: 1123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3375:3306"