spring:
  config:
    activate:
      on-profile: oauth

  security:
    oauth2:
      client:
        registration.google:
          clientId: 265541398986-insog966399112r64iq6pb93k208ofeu.apps.googleusercontent.com
          clientSecret: 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