spring.config:
  activate:
    on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        connection.provider_disables_autocommit: false
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3375/mimi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1123
    hikari:
      pool-name: HikariPool-Primary
      maximum-pool-size: 5
      connection-timeout: 5000
      connection-test-query: SELECT 1

auth:
  token.secret: FkdyWJ/KOfcNnWZ7KOkEbxeayfXzyEsSMeag84VwAeM=
  

# Oauth 정보
oauth2:
  kakao:
    client-id: 124124155cfeedfae5t513515dfe124d # 아무 값
    client-secret: 7688f0f1gW4K577613568787890123ac2zd1z #아무 값
    redirect-url: http://localhost:8080/api/v1/auth/oauth2/authorization/redirect/kakao