spring:
  profiles:
    include: oauth
    # 404 Error 를 직접 처리하기 위한 설정
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

springdoc.use-fqn: true  #Swagger에서 Schema를 Class Full Name으로 하기 위한 설정

server:
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: false


# 외부와 통신하기 위한 설정들
external:
  client:
    kakao:
      oauth2:
        profile:
          base-url: https://kauth.kakao.com
          authorization-uri: /oauth/authorize
          token-uri: /oauth/token
      kapi:
        profile:
          base-url: https://kapi.kakao.com
          user-info-uri: /v2/user/me


# Oauth 정보
oauth2:
  kakao:
    client-id: ${kakao-client-id}
    client-secret: ${kakao-client-secret}
    redirect_uri: http://localhost:8080/api/v1/auth/oauth2/authorization/redirect/kakao