spring:
  profiles:
    include: oauth
    # 404 Error 를 직접 처리하기 위한 설정
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

springdoc.use-fqn: true  #Swagger에서 Schema를 Class Full Name으로 하기 위한 설정

server:
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: false

