name: CI & CD with Google Cloud Run
on:
  push:
    branches:
      - '**' # All Branch should be checked for Integration
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - auto_merge_enabled
env:
  # Use Git Action Secret
  ## Config for OAuth2(Kakao)
  KAKAO_CLIENT_ID: ${{secrets.KAKAO_CLIENT_ID}}
  KAKAO_CLIENT_SECRET: ${{secrets.KAKAO_CLIENT_SECRET}}
  KAKAO_HTTP_HOST: ${{secrets.KAKAO_HTTP_HOST}}
#  ## GCP Secrets
#  GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
#  GCP_PROJECT_REGION: ${{secrets.GCP_PROJECT_REGION}}
#  GCP_ARTIFACT_REPOSITORY: ${{secrets.GCP_ARTIFACT_REPOSITORY}}
#  GCP_CLOUD_RUN_SERVICE: ${{secrets.GCP_CLOUD_RUN_SERVICE}}
#  GCP_CLOUD_RUN_SERVICE_ACCOUNT: ${{secrets.GCP_CLOUD_RUN_SERVICE_ACCOUNT}}
#  ## DB Secrets for GCP Cloud SQL
#  GCP_SERVERLESS_CONNECTOR: ${{secrets.GCP_SERVERLESS_CONNECTOR}}
#  GCP_CONNECTION_NAME: ${{secrets.GCP_CONNECTION_NAME}}
#  GCP_DB_PORT: ${{secrets.GCP_DB_PORT}}
#  GCP_DB_NAME: ${{secrets.GCP_DB_NAME}}
#  GCP_DB_USER: ${{secrets.GCP_DB_USER}}
#  GCP_DB_PW: ${{secrets.GCP_DB_PW}}
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      ## DB Secrets for Test
      DB_JWT_SECRET: secret
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: test_db
      DB_USER: tester
      DB_PW: '0308'
      ## Config for Build
      KAKAO_HTTP_HOST: 'localhost:8080'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java@17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Setup Mysql@8.0
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          user: ${{env.DB_USER}}
          password: ${{env.DB_PW}}
      - name: Create Database
        run: |-
          mysql --uroot -h$DB_HOST -p$DB_PORT \
            -e CREATE DATABASE $DB_NAME default CHARACTER SET UTF8;
#          mysql -u$DB_USER -p$DB_PW -h$DB_HOST -p$DB_PORT \
#            -e SHOW databases;
#  continuous-delivery:
#    # CD Job
#    runs-on: # Java & GCP
#    if: github.base_ref == 'main'
#    needs: continuous-integration



